---
title: "Financial Data Exploratory Analysis"
author: "Esteban Sánchez"
date: "18 de febrero de 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The main of this .rmd is to show the data in the db_bsm_financial.csv and study different features from the varaibles.

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(tidyverse)
library(lubridate)
library(zoo)
library(ggplot2)
library(cowplot)
```

```{r message=FALSE, warning=FALSE}
fin_data <- read_csv('../data/db_bsm_financial.csv')
fin_data$date <- as.Date(fin_data$date, format = '%Y-%m-%d')
fin_data_plot <- fin_data %>% group_by(ticker) %>% arrange(date, .by_group = TRUE) %>% 
  mutate(daily_pl = close - lag(close, default = first(close))) %>% 
  select(ticker, date, close, daily_pl, volume) %>% arrange(ticker, desc(date)) %>% mutate(year = year(date))
```

```{r}
fin_data_plot %>% filter(year > 2014 & year < 2019) %>% 
  ggplot(aes(x = ticker, y = daily_pl)) + geom_boxplot() + ylim(-10,10) + facet_grid(year~.)
```

```{r}
fin_data_plot %>% filter(year == 2017 & ticker == 'CNA.L') %>% mutate(month = month(date)) %>% 
  ggplot(aes(x = ticker, y = daily_pl)) + geom_boxplot() + facet_wrap(month~., ncol = 4)
```

```{r}
fin_data_plot %>% filter(year == 2017 & ticker == 'CPG.L') %>% mutate(month = month(date)) %>% 
  ggplot(aes(x = ticker, y = daily_pl)) + geom_boxplot() + facet_wrap(month~., ncol = 4)
```

```{r}
fin_data_plot %>% filter(year == 2017 & ticker == 'DIA.MC') %>% mutate(month = month(date)) %>% 
  ggplot(aes(x = ticker, y = daily_pl)) + geom_boxplot() + facet_wrap(month~., ncol = 4)
```

```{r}
fin_data_plot %>% filter(year == 2017 & ticker == 'EZJ.L') %>% mutate(month = month(date)) %>% 
  ggplot(aes(x = ticker, y = daily_pl)) + geom_boxplot() + facet_wrap(month~., ncol = 4)
```

```{r}
plot1 <- fin_data_plot %>% filter(year == 2018, ticker == 'CNA.L') %>%
  mutate(colour = ifelse(daily_pl < 0, '#F14D4D', '#31A02A'), 
         quant25 = quantile(daily_pl, 0.25), quant75 = quantile(daily_pl, 0.75)) %>%
  ggplot(aes(x = date)) + geom_bar(aes(y = daily_pl, fill=colour), stat = 'identity') + 
  geom_ribbon(aes(ymin = (close - daily_pl + quant25), 
                  ymax = (close - daily_pl + quant75), fill = 'orange')) + geom_line(aes(y = close)) +
  scale_fill_identity()
plot2 <- fin_data_plot %>% filter(year == 2018, ticker == 'CNA.L') %>% mutate(volume = volume / 1000000) %>% ggplot(aes(x = date, y = volume)) + 
  geom_bar(stat = 'identity')
plot_grid(plot1, plot2, align = 'v', nrow = 2, rel_heights = c(4/5, 1/5))
```

```{r}
plot1 <- fin_data_plot %>% filter(year == 2018, ticker == 'CPG.L') %>%
  mutate(colour = ifelse(daily_pl < 0, '#F14D4D', '#31A02A'), 
         quant25 = quantile(daily_pl, 0.25), quant75 = quantile(daily_pl, 0.75)) %>%
  ggplot(aes(x = date)) + geom_bar(aes(y = daily_pl, fill=colour), stat = 'identity') + 
  geom_ribbon(aes(ymin = (close - daily_pl + quant25), 
                  ymax = (close - daily_pl + quant75), fill = 'orange')) + geom_line(aes(y = close)) +
  scale_fill_identity()
plot2 <- fin_data_plot %>% filter(year == 2018, ticker == 'CPG.L') %>% mutate(volume = volume / 1000000) %>% ggplot(aes(x = date, y = volume)) + 
  geom_bar(stat = 'identity')
plot_grid(plot1, plot2, align = 'v', nrow = 2, rel_heights = c(4/5, 1/5))
```

```{r}
plot1 <- fin_data_plot %>% filter(year == 2018, ticker == 'DIA.MC') %>%
  mutate(colour = ifelse(daily_pl < 0, '#F14D4D', '#31A02A'), 
         quant25 = quantile(daily_pl, 0.25), quant75 = quantile(daily_pl, 0.75)) %>%
  ggplot(aes(x = date)) + geom_bar(aes(y = daily_pl, fill=colour), stat = 'identity') + 
  geom_ribbon(aes(ymin = (close - daily_pl + quant25), 
                  ymax = (close - daily_pl + quant75), fill = 'orange')) + geom_line(aes(y = close)) +
  scale_fill_identity()
plot2 <- fin_data_plot %>% filter(year == 2018, ticker == 'DIA.MC') %>% mutate(volume = volume / 1000000) %>% ggplot(aes(x = date, y = volume)) + 
  geom_bar(stat = 'identity')
plot_grid(plot1, plot2, align = 'v', nrow = 2, rel_heights = c(4/5, 1/5))
```

```{r}
plot1 <- fin_data_plot %>% filter(year == 2018, ticker == 'EZJ.L') %>%
  mutate(colour = ifelse(daily_pl < 0, '#F14D4D', '#31A02A'), 
         quant25 = quantile(daily_pl, 0.25), quant75 = quantile(daily_pl, 0.75)) %>%
  ggplot(aes(x = date)) + geom_bar(aes(y = daily_pl, fill=colour), stat = 'identity') + 
  geom_ribbon(aes(ymin = (close - daily_pl + quant25), 
                  ymax = (close - daily_pl + quant75), fill = 'orange')) + geom_line(aes(y = close)) +
  scale_fill_identity()
plot2 <- fin_data_plot %>% filter(year == 2018, ticker == 'EZJ.L') %>% mutate(volume = volume / 1000000) %>% ggplot(aes(x = date, y = volume)) + 
  geom_bar(stat = 'identity')
plot_grid(plot1, plot2, align = 'v', nrow = 2, rel_heights = c(4/5, 1/5))
```